ai_worker_controller:
  ros__parameters:
    control_frequency: 100.0
    time_step: 0.01
    trajectory_time: 0.0
    kp_position: 50.0
    kp_orientation: 50.0
    weight_position: 10.0
    weight_orientation: 1.0
    weight_elbow_position: 8.0
    weight_damping: 0.1
    # kp_position: 100.0
    # kp_orientation: 10.0
    # weight_position: 1.0
    # weight_orientation: 1.0
    # weight_elbow_position: 0.2
    # weight_damping: 0.1
    collision_buffer: 0.05
    collision_safe_distance: 0.02
    slack_penalty: 1000.0
    cbf_alpha: 50.0
    reactivate_topic: "/reset"  
    # reactivate_topic: "/vr_control/toggle"
    r_goal_pose_topic: "/r_goal_pose"
    l_goal_pose_topic: "/l_goal_pose"
    r_elbow_pose_topic: "/r_elbow_pose"
    l_elbow_pose_topic: "/l_elbow_pose"
    joint_states_topic: "/joint_states"
    # right_traj_topic: "/leader/joint_trajectory_command_broadcaster_right/joint_trajectory_filtered"
    # left_traj_topic: "/leader/joint_trajectory_command_broadcaster_left/joint_trajectory_filtered"
    right_traj_topic: "/leader/joint_trajectory_command_broadcaster_right/joint_trajectory"
    left_traj_topic: "/leader/joint_trajectory_command_broadcaster_left/joint_trajectory"
    r_gripper_pose_topic: "/r_gripper_pose"
    l_gripper_pose_topic: "/l_gripper_pose"
    r_gripper_name: "arm_r_link7"
    l_gripper_name: "arm_l_link7"
    r_elbow_name: "arm_r_link4"
    l_elbow_name: "arm_l_link4"
    base_frame_id: "base_link"
    traj_frame_id: ""
    right_gripper_joint: "gripper_r_joint1"
    left_gripper_joint: "gripper_l_joint1"

joint_space_controller:
  ros__parameters:
    control_frequency: 100.0
    time_step: 0.01
    trajectory_time: 0.0
    weight_tracking: 1.0
    weight_damping: 2.0
    collision_buffer: 0.05
    collision_safe_distance: 0.02
    slack_penalty: 1000.0
    cbf_alpha: 5.0
    joint_states_topic: "/joint_states"
    right_traj_topic: "/leader/joint_trajectory_command_broadcaster_right/joint_trajectory"
    left_traj_topic: "/leader/joint_trajectory_command_broadcaster_left/joint_trajectory"
    right_traj_filtered_topic: "/leader/joint_trajectory_command_broadcaster_right/joint_trajectory_filtered"
    left_traj_filtered_topic: "/leader/joint_trajectory_command_broadcaster_left/joint_trajectory_filtered"
    base_frame_id: "base_link"
    traj_frame_id: ""

reference_checker:
  ros__parameters:
    ref_pos_jump_threshold: 0.1
    ref_ori_jump_threshold_deg: 30.0
    reactivate_topic: "/reset"
    r_goal_pose_topic: "/r_goal_pose"
    l_goal_pose_topic: "/l_goal_pose"
